title: Victor's Portfolio Page
logo: /assets/NY_SCAN_2022.jpg
description: This is me.
show downloads: True
#theme: jekyll-theme-minimal
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
