title: Victor Karamalis
logo: assets/IMG20240304175638.jpg
description: Email - victor@karamalis.me
description: T: (954)707-7545, E:- victor@karamalis.me
#show downloads: true
theme: jekyll-theme-minimal

