title: Victor Karamalis
#logo:/ assets/img/victor_2024.pmg
description: Data Management
show_downloads:true



# Sample workflow for building and deploying a Jekyll site to GitHub Pages
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

